#ifndef GLOBALS_H
#define GLOBALS_H

//DO NOT EDIT THIS FILE ******************************
// OpenWeatherOneCall v4.0.0


extern float myLATITUDE;
extern float myLONGITUDE;
extern int myCITYID;
extern int myUNITS;
extern int myDTF;
extern int myTimeZone;
extern int myTIMESTAMP;
extern int myCURRENT;
extern int myAIRQUALITY;
extern char timestampDate[11];
extern int myOVERVIEW;
extern char overviewDate[9];
extern int myEXCLUDES;
extern char ONECALLKEY[];
extern int locationMode;


#endif // GLOBALS_H
